contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      'https://github.com/syscoin/pali-wallet/issues'
  - about: Get support on the Syscoin chat channels on Discord.
    name: Join the Syscoin support chat
    url: 'https://discord.com/invite/syscoin'
